services:

  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://${DB_USER:-admin}:${DB_PASS:-adminpassword}@postgres:5432/${DB_NAME:-hotel}
    depends_on:
      - postgres
    volumes:
      - uploads_data:/app/uploads  # 🆕 uploads volume

  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-hotel}  # Updated to match the new DB_NAME
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASS:-adminpassword}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  uploads_data:  # 🆕 uploads volume
